# Generated by Django 3.2.4 on 2022-09-24 01:51

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Price')),
                ('img', cloudinary.models.CloudinaryField(max_length=255, verbose_name='Image')),
                ('categories', models.CharField(choices=[('hot', 'Hot'), ('bagel', 'Bagel'), ('cold', 'Cold')], max_length=100, verbose_name='Category')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Datetime')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Datetime')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('deleted', 'Deleted')], db_index=True, default='draft', max_length=50, verbose_name='Status')),
            ],
        ),
        migrations.DeleteModel(
            name='Items',
        ),
    ]
